version: '2'

services:

    main:
        image: puffinrocks/owncloud:9.1.4
        ports: 
            - 80
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=80
        networks:
            - front
            - back
            - default
        volumes: 
            - main_data:/var/www/html
        tmpfs:
            - /tmp
            #- /run - can't do that due to https://github.com/docker-library/php/issues/250

volumes:
    main_data:

networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"
