version: '2'

services:

    main:
        image: puffinrocks/owncloud
        ports: 
            - 80
        volumes: 
            - main_data:/var/www/html
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=80
        networks:
            - front
            - back
            - default

volumes:
    main_data:

networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"
