version: '2'

labels:

    rocks.puffin.name: ownCloud 
    rocks.puffin.subtitle: file sync and share server
    rocks.puffin.website: https://owncloud.org/ 
    rocks.puffin.description: |
        A safe home for all your data. 
        Access & share your files, calendars, contacts, mail & more from any device, on your terms.

services:

    main:
        image: loomchild/owncloud
        ports: 
            - 80
        volumes: 
            - main_data:/var/www/html
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=80
        networks:
            - front
            - back
            - default

volumes:
    main_data:

networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"
